FROM ubuntu:trusty

RUN apt-get -y update
RUN apt-get -y install htop curl git mercurial lsof wget vim
RUN apt-get clean

# new-relic
RUN echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
RUN wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
RUN apt-get update
RUN apt-get install newrelic-sysmond
RUN nrsysmond-config --set license_key="NOLICENSEKEYNOLICENSEKEYNOLICENSEKEYNOLI"

# startup
ADD misc/startup.sh /
RUN chmod 755 /startup.sh

CMD ["/startup.sh"]
